### ISSUE TITLE
What API-methods are exposed to Node?

### ISSUE THREAD

**Issue by unagitated** [mdelete/node-tesseract-native#4]
Hi,
thanks for this project. I got the Hello World test up and running smoothly using node-gyp.
However, I wonder how to reach all methods of Tesseracts API, such as SetRectangle (tesseract::TessBaseAPI::SetRectangle (int left, int top, int width, int height))?
Thanks.
/Peter

**Comment by mdelete** [comment]
Unfortunately, this module is older than google's renewed interest in tesseract. It still uses the legacy API and only exposes the ProcessPage method and some config options. I'll adapt it to the nicer getter/setter API in the future, but it may take some time. What would you need apart from SetRectangle?

**Comment by unagitated** [comment]
Ok, I see.
I am new to Tesseract, and therefore do not yet know what functionality I will need, but I know for sure that the SetRectangle would be useful, if not using some other library, such as ImageMagick, to first crop out smaller images containing relevant areas of the original image.
I do not know anything about the CPP-Node work that need be done, but of course I am thankful for work made by people like you. Would it suffice to change the files in this repository or are other dependencies needed to get SetRectangle working? I looked at https://kkaefer.com/node-cpp-modules/#catch-fatalexception but to me this looks complicated. Do you have a public email address or a more suitable forum for this type of discussion?
/Peter

**Comment by mdelete** [comment]
I added a rect parameter to master (not in the npm version yet), it should get you what you need. See README.

**Comment by unagitated** [comment]
Great work! I will try it out.
