### ISSUE TITLE
Hope to have an option to  recognize only numbers

### ISSUE THREAD

**Issue by halfcrazy** [mdelete/node-tesseract-native#7]
this option would have the same behaviour as `$ tesseract imagename outputbase digits` does

**Comment by Zougi** [comment]
If I read the sources correctly, it's
```
var options;
options = {
  config: 'digits'  
};
tesseract.process('myImage.tiff', options,
            function(err, text) {
                if (err) {
                    console.error(err);
                } else {
                    console.log(text);
                }
            });
```
This should be documented

**Comment by halfcrazy** [comment]
@Zougi Thanks, I'll have a try.

**Comment by Zougi** [comment]
I just noticed I have replied on node-tesseract-NATIVE. I thought I was on node-tesseract repo..my mistake. It doesn't seem to me that node-tesseract-native has this functionality yet

**Comment by halfcrazy** [comment]
@Zougi oops, I just read the code, and find it has an optional paramater which could be a config dict.
such as {lang:'eng'} https://github.com/mdelete/node-tesseract-native/blob/master/node-tesseract-native.cc#L101, but i wondered if it support paramater like {config:'digits'} or {lang:'digits'}

**Comment by Zougi** [comment]
I only see "lang", "tessdata" and "rect". node-tesseract-native should implement ReadConfigFile from baseapi. https://github.com/tesseract-ocr/tesseract/blob/master/api/baseapi.h It should not be too complicated to implement it yourself. I personally use node-tesseract. I don't need async workflow.

**Comment by TheDolo** [comment]
@mdelete bump, this library feels useless without being able to config Tesseract.
