### ISSUE TITLE
while the homebrew version of tesseract is 3.04, and it seems dismatch the requirement.

### ISSUE THREAD

**Issue by halfcrazy** [mdelete/node-tesseract-native#8]
> tesseract_native@0.4.1 preinstall /Users/eleme/workspace/city_fetcher/node_modules/tesseract_native
> node-gyp configure && node-gyp build

  CXX(target) Release/obj.target/tesseract_native/node-tesseract-native.o
../node-tesseract-native.cc:16:16: error: expected class name
class OcrEio : ObjectWrap
               ^
../node-tesseract-native.cc:44:34: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> New(const Arguments& args)
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/Users/eleme/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-tesseract-native.cc:65:34: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> Ocr(const Arguments& args)
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/Users/eleme/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-tesseract-native.cc:187:23: error: unknown type name 'uv_work_t'
  static void EIO_Ocr(uv_work_t *req)
                      ^
../node-tesseract-native.cc:217:28: error: unknown type name 'uv_work_t'
  static void EIO_AfterOcr(uv_work_t *req, int status)
                           ^
../node-tesseract-native.cc:23:55: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'Handle<v8::Value> (const v8::internal::Arguments &)'
    Local<FunctionTemplate> t = FunctionTemplate::New(New);
                                                      ^~~
/Users/eleme/.node-gyp/0.12.7/deps/v8/include/v8.h:3456:16: note: passing argument to parameter 'isolate' here
      Isolate* isolate,
               ^
../node-tesseract-native.cc:25:42: error: 'New' is a private member of 'v8::PersistentBase<v8::FunctionTemplate>'
    s_ct = Persistent<FunctionTemplate>::New(t);
                                         ^
/Users/eleme/.node-gyp/0.12.7/deps/v8/include/v8.h:572:23: note: declared private here
  V8_INLINE static T* New(Isolate* isolate, T* that);
                      ^
../node-tesseract-native.cc:25:12: error: too few arguments to function call, expected 2, have 1; did you mean '::OcrEio::New'?
    s_ct = Persistent<FunctionTemplate>::New(t);
           ^~~~~~~~~~
           ::OcrEio::New
../node-tesseract-native.cc:44:24: note: '::OcrEio::New' declared here
  static Handle<Value> New(const Arguments& args)
                       ^
../node-tesseract-native.cc:26:9: error: member reference type 'Persistent<v8::FunctionTemplate>' is not a pointer; maybe you meant to use '.'?
    s_ct->InstanceTemplate()->SetInternalFieldCount(1);
    ~~~~^~
        .
../node-tesseract-native.cc:26:11: error: no member named 'InstanceTemplate' in 'v8::Persistent<v8::FunctionTemplate, v8::NonCopyablePersistentTraits<v8::FunctionTemplate> >'
    s_ct->InstanceTemplate()->SetInternalFieldCount(1);
    ~~~~  ^
../node-tesseract-native.cc:27:9: error: member reference type 'Persistent<v8::FunctionTemplate>' is not a pointer; maybe you meant to use '.'?
    s_ct->SetClassName(String::NewSymbol("OcrEio"));
    ~~~~^~
        .
../node-tesseract-native.cc:27:11: error: no member named 'SetClassName' in 'v8::Persistent<v8::FunctionTemplate, v8::NonCopyablePersistentTraits<v8::FunctionTemplate> >'
    s_ct->SetClassName(String::NewSymbol("OcrEio"));
    ~~~~  ^
../node-tesseract-native.cc:27:32: error: no member named 'NewSymbol' in 'v8::String'
    s_ct->SetClassName(String::NewSymbol("OcrEio"));
                       ~~~~~~~~^
../node-tesseract-native.cc:29:31: error: no viable conversion from 'Persistent<v8::FunctionTemplate>' to 'v8::Handle<v8::FunctionTemplate>'
    NODE_SET_PROTOTYPE_METHOD(s_ct, "ocr", Ocr);
                              ^~~~
/Users/eleme/.node-gyp/0.12.7/deps/v8/include/v8.h:196:26: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from
      'Persistent<v8::FunctionTemplate>' to 'const v8::Handle<v8::FunctionTemplate> &' for 1st argument
template <class T> class Handle {
                         ^
/Users/eleme/.node-gyp/0.12.7/deps/v8/include/v8.h:213:32: note: candidate template ignored: could not match 'Handle' against 'Persistent'
  template <class S> V8_INLINE Handle(Handle<S> that)
                               ^
/Users/eleme/.node-gyp/0.12.7/src/node.h:244:72: note: passing argument to parameter 'recv' here
inline void NODE_SET_PROTOTYPE_METHOD(v8::Handle<v8::FunctionTemplate> recv,
                                                                       ^
../node-tesseract-native.cc:31:25: error: no member named 'NewSymbol' in 'v8::String'
    target->Set(String::NewSymbol("OcrEio"), s_ct->GetFunction());
                ~~~~~~~~^
../node-tesseract-native.cc:31:50: error: member reference type 'Persistent<v8::FunctionTemplate>' is not a pointer; maybe you meant to use '.'?
    target->Set(String::NewSymbol("OcrEio"), s_ct->GetFunction());
                                             ~~~~^~
                                                 .
../node-tesseract-native.cc:31:52: error: no member named 'GetFunction' in 'v8::Persistent<v8::FunctionTemplate, v8::NonCopyablePersistentTraits<v8::FunctionTemplate> >'
    target->Set(String::NewSymbol("OcrEio"), s_ct->GetFunction());
                                             ~~~~  ^
../node-tesseract-native.cc:46:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/eleme/.node-gyp/0.12.7/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../node-tesseract-native.cc:48:9: error: no member named 'Wrap' in 'OcrEio'
    oe->Wrap(args.This());
    ~~  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/tesseract_native/node-tesseract-native.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /Users/eleme/workspace/city_fetcher/node_modules/tesseract_native
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! tesseract_native@0.4.1 preinstall: `node-gyp configure && node-gyp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tesseract_native@0.4.1 preinstall script 'node-gyp configure && node-gyp build'.
npm ERR! This is most likely a problem with the tesseract_native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure && node-gyp build
npm ERR! You can get their info via:
npm ERR!     npm owner ls tesseract_native
npm ERR! There is likely additional logging output above.

> tesseract_native@0.4.1 preuninstall /Users/eleme/workspace/city_fetcher/node_modules/tesseract_native
> rm -rf build/*


npm ERR! Please include the following file with any support request:
npm ERR!     /Users/eleme/workspace/city_fetcher/npm-debug.log

**Comment by mdelete** [comment]
Hi! I'll have to look into it. The npm shouldn't pull the 0.4.1 version of this package because it is incompatible with node 0.12.x. The current node versions above 0.11.x need 0.5.0, which is in the `node12` branch of tesseract_native.

**Comment by mdelete** [comment]
0.5.0 should be the default, but could you try to force it? `npm install tesseract_native@0.5.0`

**Comment by halfcrazy** [comment]
@mdelete amazing！after trying `npm install tesseract_native@0.5.0` the package installs successfully.

**Comment by dantheman213** [comment]
should I run
````
npm install tesseract_native@0.5.0
````

in lieu of 
````
npm install tesseract
````
?

**Comment by halfcrazy** [comment]
@dantheman213 If you want the lastest version, you may just type `npm install tesseract_native` or `npm install tesseract_native@0.5.2`

```json
{
  "name" : "tesseract_native",
  "description" : "C++ module for node providing OCR with tesseract and leptonica",
  "version" : "v0.5.2",
  "gypfile": true,
  "scripts" : {
    "test": "node test.js HelloWorld.jpg"
  }
```
