### ISSUE TITLE
TypeError: Argument 1 must be an object of type Buffer

### ISSUE THREAD

**Issue by halfcrazy** [mdelete/node-tesseract-native#9]
as shown below. My first param passed to myocr.ocr is an object of type buffer. What's wrong?

root@wxw120:~/workspace/city_fetcher# node app.js
Tesseract Open Source OCR Engine v3.03 with Leptonica
listening 5000
\<Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 00 00 01 00 01 00 00 ff db 00 43 00 08 06 06 07 06 05 08 07 07 07 09 09 08 0a 0c 14 0d 0c 0b 0b 0c 19 12 13 0f ... \>
/root/workspace/city_fetcher/common/simulate_login.js:33
        myOcr.ocr(res1.body, function(err2, result) {
              ^

TypeError: Argument 1 must be an object of type Buffer
    at TypeError (native)
    at /root/workspace/city_fetcher/common/simulate_login.js:33:15
    at Request.callback (/root/workspace/city_fetcher/node_modules/superagent/lib/node/index.js:785:12)
    at /root/workspace/city_fetcher/node_modules/superagent/lib/node/index.js:929:14
    at IncomingMessage.<anonymous> (/root/workspace/city_fetcher/node_modules/superagent/lib/node/parsers/image.js:8:7)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:430:9)
    at process._tickCallback (node.js:344:17)

**Comment by halfcrazy** [comment]
node version is 4.1.2

**Comment by br1ckb0t** [comment]
I'm seeing the same thing on Node v4.2.2

**Comment by nbrustein** [comment]
me too with node 5.4.1

**Comment by LaneTwo** [comment]
I also met the same issue in Node 4.2.1, but no issue in Node 1.2.1.
I tried to resolve that here, seems work fine now:
https://github.com/LaneTwo/node-tesseract-native/commit/013b384ffc6fd0a6bb0ea7576b4b7ca0e6da458a

You can modify the ocreio.cc under node_modules/tesseract_native and rebuild it(node-gyp build).
Hope that resolve your issue.

**Comment by mdelete** [comment]
Fixed with merged pull request #12
